import 'package:flutter/material.dart';

const top1 = 'assets/top1.png';
const top2 = 'assets/top2.png';
const top3 = 'assets/top3.png';
const top4 = 'assets/top4.png';
const cake1 = 'assets/cake1.png';
const cake2 = 'assets/cake2.png';
const cake3 = 'assets/cake3.png';
const cake4 = 'assets/cake4.png';
const cake5 = 'assets/cake5.png';
const cake6 = 'assets/cake6.png';
const cake7 = 'assets/cake7.png';
const cake8 = 'assets/cake8.png';
const bakery = 'assets/Bakery.png';
const categories = 'assets/Brezel.png';
const orders = 'assets/Breakfast.png';
const profile = 'assets/User.png';
const frame1 = 'assets/Frame6.png';
const frame2 = 'assets/Frame7.png';
const frame3 = 'assets/Frame8.png';
const frame4 = 'assets/Frame9.png';
const frame5 = 'assets/Frame10.png';
const frame6 = 'assets/Frame11.png';
const order = 'assets/order1.png';
const imageProfile = 'assets/profile.png';
